apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: prom
  name: ovh-mks-etcd-quota
  namespace: observability
spec:
  groups:
    - name: ovh-mks-etcd-quota.rules
      rules:
        - alert: OvhMksEtcdQuotaWarning
          annotations:
            description: >-
              OVH MKS ETCD Quota for cluster "{{ $labels.name }}" is more than {{ $value | humanize }} %.
            summary: OVH MKS ETCD Quota exceeds 75 %
          expr: >-
            (avg_over_time(ovh_mks_etcd_usage_usage_bytes[5m]) / avg_over_time(ovh_mks_etcd_usage_quota_bytes[5m])) * 100 > 75
          for: 10m
          labels:
            severity: warning
        - alert: OvhMksEtcdQuotaCritical
          annotations:
            description: >-
              OVH MKS ETCD Quota for cluster "{{ $labels.name }}" is more than {{ $value | humanize }} %.
            summary: OVH MKS ETCD Quota exceeds 90 %
          expr: >-
            (avg_over_time(ovh_mks_etcd_usage_usage_bytes[5m]) / avg_over_time(ovh_mks_etcd_usage_quota_bytes[5m])) * 100 > 90
          for: 10m
          labels:
            severity: critical

