before:
  hooks:
    - go mod vendor
builds:
  - binary: bin/ovh-mks-exporter
    main: ./cmd/ovh-mks-exporter/main.go
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
    goos:
      - linux
    goarch:
      - amd64
      - arm64
checksum:
  name_template: 'checksums.txt'
