{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.ServiceMonitor.prometheusReleaseName }}-{{ include "ovh-mks-exporter.fullname" . }}
  labels:
    {{- include "ovh-mks-exporter.labels" . | nindent 4 }}
    release: {{ .Values.ServiceMonitor.prometheusReleaseName }}
spec:
  endpoints:
    - port: http-metrics
      interval: 180s
      scrapeTimeout: 60s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
    {{- include "ovh-mks-exporter.selectorLabels" . | nindent 4 }}
{{- end }}
