apiVersion: v1
kind: Service
metadata:
  name: ovh-mks-exporter
  labels:
    app.kubernetes.io/instance: ovh-mks-exporter
    app.kubernetes.io/name: ovh-mks-exporter
    app.kubernetes.io/version: 1.3.1
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics
    port: 9101
    protocol: TCP
    targetPort: http-metrics
  selector:
    app.kubernetes.io/instance: ovh-mks-exporter
    app.kubernetes.io/name: ovh-mks-exporter
