apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: ovh-mks-exporter
    app.kubernetes.io/name: ovh-mks-exporter
    app.kubernetes.io/version: 1.3.3
    release: prom
  name: prom-ovh-mks-exporter
spec:
  endpoints:
    - port: http-metrics
      interval: 180s
      scrapeTimeout: 60s
  namespaceSelector:
    matchNames:
      - observability
  selector:
    matchLabels:
      app.kubernetes.io/instance: ovh-mks-exporter
      app.kubernetes.io/name: ovh-mks-exporter
